apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui-service
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31513
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - image: provectuslabs/kafka-ui
          imagePullPolicy: IfNotPresent
          name: kafka-ui
          ports:
            - containerPort: 8080
          env:
          - name: DYNAMIC_CONFIG_ENABLED
            value: 'true'
          - name: KAFKA_CLUSTERS_0_NAME
            value: local
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: kafka-service:29092
          resources:
            limits:
              memory: 256Mi
              cpu: "500m"
    