apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-user-service
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: mongo-user-port
      port: 27017
      targetPort: 27017