apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-mongodb-user"
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
