apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181